server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    # Optional static route example
    # routes:
    #   - id: account-service
    #     uri: http://localhost:8080
    #     predicates:
    #       - Path=/accounts/**
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
